[package]
name = "lox_byte"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
all = ["trace", "debug", "scanner_debug"]
trace = []
debug = []
scanner_debug = []

[dependencies]
